package(default_visibility = ["//visibility:public"])

load("//tools:build_rules/go.bzl", "go_binary")

go_binary(
    name = "main",
    srcs = [
        "main.go",
    ],
    deps = [
	"//lib",
    ],
)


